# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_test_name.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../00_test_name.ipynb 3
def foo(): pass

# %% ../00_test_name.ipynb 4
def say_hello(to):
    "say hello to somebody"
    return f'Hello {to}!'
